In [1]:
import pandas as pd
import numpy as np

#Carregando csv de vendedores
df_sellers = pd.read_csv("../data/staging/sellers.csv", encoding="UTF-8")

display(df_sellers)

,seller_id,seller_zip_code_prefix,seller_city,seller_state
0,3442f8959a84dea7ee197c632cb2df15,13023,campinas,SP
1,d1b65fc7debc3361ea86b5f14c68d2e2,13844,mogi guacu,SP
2,ce3ad9de960102d0677a81f5d0bb7b2d,20031,rio de janeiro,RJ
3,c0f3eea2e14555b6faeea3dd58c1b1c3,4195,sao paulo,SP
4,51a04a8a6bdcb23deccc82b0b80742cf,12914,braganca paulista,SP
...,...,...,...,...
3090,98dddbc4601dd4443ca174359b237166,87111,sarandi,PR
3091,f8201cab383e484733266d1906e2fdfa,88137,palhoca,SC
3092,74871d19219c7d518d0090283e03c137,4650,sao paulo,SP
3093,e603cf3fec55f8697c9059638d6c8eb5,96080,pelotas,RS
3094,9e25199f6ef7e7c347120ff175652c3b,12051,taubate,SP

In [2]:
#Análise Inicial dos dados
print("Quantidade de colunas - ")

display(df_sellers.shape)
display(list(df_sellers.columns))
columns = list(df_sellers.columns)

print("Descrição das tabelas - ")

display(df_sellers.info())
display(df_sellers.describe())
print("Soma dos valores NULL de cada coluna - ")
display(df_sellers.isnull().sum())
print("Soma dos valores NAN de cada coluna - ")
display(df_sellers.isna().sum())

print(f"Soma dos valores duplicados: {df_sellers['seller_id'].duplicated().sum()}")

Quantidade de colunas -

(3095, 4)

['seller_id', 'seller_zip_code_prefix', 'seller_city', 'seller_state']

Descrição das tabelas -
<class 'pandas.DataFrame'>
RangeIndex: 3095 entries, 0 to 3094
Data columns (total 4 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   seller_id               3095 non-null   str
 1   seller_zip_code_prefix  3095 non-null   int64
 2   seller_city             3095 non-null   str
 3   seller_state            3095 non-null   str
dtypes: int64(1), str(3)
memory usage: 96.8 KB

None

       seller_zip_code_prefix
count             3095.000000
mean             32291.059451
std              32713.453830
min               1001.000000
25%               7093.500000
50%              14940.000000
75%              64552.500000
max              99730.000000

Soma dos valores NULL de cada coluna -

seller_id                 0
seller_zip_code_prefix    0
seller_city               0
seller_state              0
dtype: int64

Soma dos valores NAN de cada coluna -

seller_id                 0
seller_zip_code_prefix    0
seller_city               0
seller_state              0
dtype: int64

Soma dos valores duplicados: 0

In [3]:
#Limpeza dos dados

df_sellers['seller_zip_code_prefix'] = df_sellers['seller_zip_code_prefix'].astype(str).str.replace(r'\.0$', '', regex=True)
df_sellers['seller_zip_code_prefix'] = df_sellers['seller_zip_code_prefix'].str.zfill(5)
df_sellers['seller_city'] = df_sellers['seller_city'].str.strip()
df_sellers['seller_city'] = df_sellers['seller_city'].str.title()
df_sellers['seller_state'] = df_sellers['seller_state'].str.strip()
df_sellers['seller_zip_code_prefix'] = df_sellers['seller_zip_code_prefix'].str.strip()
display(df_sellers)

,seller_id,seller_zip_code_prefix,seller_city,seller_state
0,3442f8959a84dea7ee197c632cb2df15,13023,Campinas,SP
1,d1b65fc7debc3361ea86b5f14c68d2e2,13844,Mogi Guacu,SP
2,ce3ad9de960102d0677a81f5d0bb7b2d,20031,Rio De Janeiro,RJ
3,c0f3eea2e14555b6faeea3dd58c1b1c3,04195,Sao Paulo,SP
4,51a04a8a6bdcb23deccc82b0b80742cf,12914,Braganca Paulista,SP
...,...,...,...,...
3090,98dddbc4601dd4443ca174359b237166,87111,Sarandi,PR
3091,f8201cab383e484733266d1906e2fdfa,88137,Palhoca,SC
3092,74871d19219c7d518d0090283e03c137,04650,Sao Paulo,SP
3093,e603cf3fec55f8697c9059638d6c8eb5,96080,Pelotas,RS
3094,9e25199f6ef7e7c347120ff175652c3b,12051,Taubate,SP

In [4]:
df_sellers.to_csv("../data/processed/sellers_processed.csv")